
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bigjo
 */
public class ChangeInfoForm extends javax.swing.JFrame {

    /**
     * Creates new form ChangeInfoForm
     */
    public ChangeInfoForm() {
        initComponents();
        lbl_FN.setVisible(false);
        lbl_LN.setVisible(false);
        lbl_Sex.setVisible(false);
        lbl_Add.setVisible(false);
        lbl_Ph.setVisible(false);
        lbl_Bd.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel_LastName = new javax.swing.JLabel();
        jLabel_FirstName = new javax.swing.JLabel();
        jLabel_Address = new javax.swing.JLabel();
        jLabel_Bday = new javax.swing.JLabel();
        jLabel_Sex = new javax.swing.JLabel();
        jLabel_Phone = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField_LastName = new javax.swing.JTextField();
        jTextField_FirstName = new javax.swing.JTextField();
        jTextField_Sex = new javax.swing.JTextField();
        jTextField_Address = new javax.swing.JTextField();
        jTextField_Phone = new javax.swing.JTextField();
        jDateChooser_Bday = new com.toedter.calendar.JDateChooser();
        jButton_Exit = new javax.swing.JButton();
        jButton_FirstName = new javax.swing.JButton();
        jButton_LastName = new javax.swing.JButton();
        jButton_Sex = new javax.swing.JButton();
        jButton_Address = new javax.swing.JButton();
        jButton_Phone = new javax.swing.JButton();
        jButton_Bday = new javax.swing.JButton();
        lbl_Bd = new javax.swing.JLabel();
        lbl_Ph = new javax.swing.JLabel();
        lbl_Add = new javax.swing.JLabel();
        lbl_Sex = new javax.swing.JLabel();
        lbl_LN = new javax.swing.JLabel();
        lbl_FN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Modify User Account Data");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("New First Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Current Last Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Current Sex:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Current Address:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Current Phone:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Current Birthday:");

        jLabel_LastName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_LastName.setText("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");

        jLabel_FirstName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_FirstName.setText("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");

        jLabel_Address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Address.setText("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");

        jLabel_Bday.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Bday.setText("XXXXXXXXXX-XX-XXXX");

        jLabel_Sex.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Sex.setText("X");

        jLabel_Phone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Phone.setText("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Current First Name:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("New Last Name:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("New Sex:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("New Address:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("New Phone:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("New Birthday:");

        jTextField_LastName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_FirstName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_Sex.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_Address.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_Phone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButton_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Remove.png"))); // NOI18N
        jButton_Exit.setText("Close");
        jButton_Exit.setIconTextGap(10);
        jButton_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExitActionPerformed(evt);
            }
        });

        jButton_FirstName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_FirstName.setText("Update");
        jButton_FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FirstNameActionPerformed(evt);
            }
        });

        jButton_LastName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_LastName.setText("Update");
        jButton_LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LastNameActionPerformed(evt);
            }
        });

        jButton_Sex.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_Sex.setText("Update");
        jButton_Sex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SexActionPerformed(evt);
            }
        });

        jButton_Address.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_Address.setText("Update");
        jButton_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddressActionPerformed(evt);
            }
        });

        jButton_Phone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_Phone.setText("Update");
        jButton_Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PhoneActionPerformed(evt);
            }
        });

        jButton_Bday.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_Bday.setText("Update");
        jButton_Bday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BdayActionPerformed(evt);
            }
        });

        lbl_Bd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Bd.setForeground(new java.awt.Color(255, 0, 51));
        lbl_Bd.setText("*");

        lbl_Ph.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Ph.setForeground(new java.awt.Color(255, 0, 51));
        lbl_Ph.setText("*");

        lbl_Add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Add.setForeground(new java.awt.Color(255, 0, 51));
        lbl_Add.setText("*");

        lbl_Sex.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Sex.setForeground(new java.awt.Color(255, 0, 51));
        lbl_Sex.setText("*");

        lbl_LN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_LN.setForeground(new java.awt.Color(255, 0, 51));
        lbl_LN.setText("*");

        lbl_FN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_FN.setForeground(new java.awt.Color(255, 0, 51));
        lbl_FN.setText("*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(166, 166, 166))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jDateChooser_Bday, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_Bd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Bday))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_Add)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Address))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel_LastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_FirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_Address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_Bday)
                                    .addComponent(jLabel_Sex)
                                    .addComponent(jLabel_Phone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField_LastName)
                                    .addComponent(jTextField_FirstName)
                                    .addComponent(jTextField_Phone)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField_Sex, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_Sex)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_Sex)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_Ph)
                                        .addGap(4, 4, 4)
                                        .addComponent(jButton_Phone))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lbl_LN)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton_LastName))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lbl_FN)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton_FirstName))))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jButton_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_FirstName)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel_LastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel_Sex))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel_Address))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel_Phone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel_Bday))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_FirstName)
                    .addComponent(lbl_FN))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_LastName)
                    .addComponent(lbl_LN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField_Sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Sex)
                    .addComponent(lbl_Sex))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jTextField_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Address)
                            .addComponent(lbl_Add))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jTextField_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Phone)
                            .addComponent(lbl_Ph))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(jDateChooser_Bday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_Bday)
                        .addComponent(lbl_Bd)))
                .addGap(54, 54, 54)
                .addComponent(jButton_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_ExitActionPerformed

    private void jButton_FirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FirstNameActionPerformed
        // TODO add your handling code here:
        lbl_FN.setVisible(false);
        if(jTextField_FirstName.getText().equals(""))
        {
            lbl_FN.setVisible(true);
        }
        else
        {
            String fn = jTextField_FirstName.getText();
            jLabel_FirstName.setText(fn);
            /**@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ DO DATABASE STUFF TO CHANGE FIRST NAME HERE @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@**/
        }
    }//GEN-LAST:event_jButton_FirstNameActionPerformed

    private void jButton_LastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LastNameActionPerformed
        // TODO add your handling code here:
        lbl_LN.setVisible(false);
        if(jTextField_LastName.getText().equals(""))
        {
            lbl_LN.setVisible(true);
        }
        else
        {
            String temp = jTextField_LastName.getText();
            jLabel_LastName.setText(temp);
            /**@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ DO DATABASE STUFF TO CHANGE LAST NAME HERE @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@**/
        }
    }//GEN-LAST:event_jButton_LastNameActionPerformed

    private void jButton_SexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SexActionPerformed
        // TODO add your handling code here:
        lbl_Sex.setVisible(false);
        if(jTextField_Sex.getText().equals(""))
        {
            lbl_Sex.setVisible(true);
        }
        else
        {
            char temp = jTextField_Sex.getText().charAt(0);
            jLabel_Sex.setText(""+temp);
            /**@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ DO DATABASE STUFF TO CHANGE SEX HERE @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@**/
        }
    }//GEN-LAST:event_jButton_SexActionPerformed

    private void jButton_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddressActionPerformed
        // TODO add your handling code here:
        lbl_Add.setVisible(false);
        if(jTextField_Address.getText().equals(""))
        {
            lbl_Add.setVisible(true);
        }
        else
        {
            String temp = jTextField_Address.getText();
            jLabel_Address.setText(temp);
            /**@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ DO DATABASE STUFF TO CHANGE ADDRESS HERE @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@**/
        }
    }//GEN-LAST:event_jButton_AddressActionPerformed

    private void jButton_PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PhoneActionPerformed
        // TODO add your handling code here:
        lbl_Ph.setVisible(false);
        if(jTextField_Phone.getText().equals(""))
        {
            lbl_Ph.setVisible(true);
        }
        else
        {
            String temp = jTextField_Phone.getText();
            jLabel_Phone.setText(temp);
            /**@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ DO DATABASE STUFF TO CHANGE PHONE HERE @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@**/
        }
    }//GEN-LAST:event_jButton_PhoneActionPerformed

    private void jButton_BdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BdayActionPerformed
        // TODO add your handling code here:
        lbl_Bd.setVisible(false);
        if(jDateChooser_Bday == null)
        {
            lbl_Bd.setVisible(true);
        }
        else
        {
            String temp = ((JTextField)jDateChooser_Bday.getDateEditor().getUiComponent()).getText();
            jLabel_Bday.setText(temp);
            /**@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ DO DATABASE STUFF TO CHANGE BIRTHDAY HERE @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@**/
        }
    }//GEN-LAST:event_jButton_BdayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeInfoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeInfoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeInfoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeInfoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeInfoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Address;
    private javax.swing.JButton jButton_Bday;
    private javax.swing.JButton jButton_Exit;
    private javax.swing.JButton jButton_FirstName;
    private javax.swing.JButton jButton_LastName;
    private javax.swing.JButton jButton_Phone;
    private javax.swing.JButton jButton_Sex;
    private com.toedter.calendar.JDateChooser jDateChooser_Bday;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel_Address;
    public static javax.swing.JLabel jLabel_Bday;
    public static javax.swing.JLabel jLabel_FirstName;
    public static javax.swing.JLabel jLabel_LastName;
    public static javax.swing.JLabel jLabel_Phone;
    public static javax.swing.JLabel jLabel_Sex;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_Address;
    private javax.swing.JTextField jTextField_FirstName;
    private javax.swing.JTextField jTextField_LastName;
    private javax.swing.JTextField jTextField_Phone;
    private javax.swing.JTextField jTextField_Sex;
    private javax.swing.JLabel lbl_Add;
    private javax.swing.JLabel lbl_Bd;
    private javax.swing.JLabel lbl_FN;
    private javax.swing.JLabel lbl_LN;
    private javax.swing.JLabel lbl_Ph;
    private javax.swing.JLabel lbl_Sex;
    // End of variables declaration//GEN-END:variables
}
